# Trainings I attended

- name: Docker image best practices
  where: JAC Experts

- name: GitLab CI Pipelines best practices
  where: JAC Experts

- name: Rancher & RKE best practices
  where: JAC Experts

- name: Velero best practices
  where: JAC Experts

- name: Kanban Offical LKU
  where: LKU